-- 删除所有现有表（如果存在）
DROP TABLE IF EXISTS cells CASCADE;
DROP TABLE IF EXISTS rows CASCADE;
DROP TABLE IF EXISTS fields CASCADE;
DROP TABLE IF EXISTS sheets CASCADE;
DROP TABLE IF EXISTS verification CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS users CASCADE;
